#!/usr/bin/env python3
"""Render the reviewed data-start set as Rust; never infer safety from generation.

The input membership is separately derived and integration-tested. --check
verifies the checked-in executable representation without loading native code.
"""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "tests/unicode-policy-probe/start-candidate.json"
DESTINATION = ROOT / "src/github_actions/stdout_start_table.rs"

def render(raw):
    data = json.loads(raw)
    ranges = data["ranges"]
    count = 0
    previous = -1
    for start, end in ranges:
        if (type(start) is not int or type(end) is not int or not 0 < start <= end <= 0x10ffff
                or start <= previous + 1 or start <= 0xdfff and end >= 0xd800):
            raise ValueError("invalid or noncanonical range")
        count += end - start + 1
        previous = end
    if count != data["count"] or not ranges:
        raise ValueError("membership count mismatch")
    lines = ["// Generated by scripts/generate-stdout-start-table.py; do not edit.",
             "// Source SHA256: " + hashlib.sha256(raw).hexdigest(),
             "// Membership applicability: docs/compatibility/stdout-unicode-policy.md.",
             "pub(super) const START_RANGES: &[(u32, u32)] = &["]
    lines.extend(f"    (0x{start:04x}, 0x{end:04x})," for start, end in ranges)
    return "\n".join(lines + ["];", ""])

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = render(SOURCE.read_bytes())
    if args.check:
        if DESTINATION.read_text() != generated:
            raise ValueError("generated table differs")
    else:
        DESTINATION.write_text(generated)

if __name__ == "__main__":
    main()
